# Roster data for webookshows.com. Every fact here was checked against Wikipedia,
# Wikidata, official artist sites or label/VEVO channels (Sept 2026).
# Leave a field out rather than guessing. No fees or prices anywhere.

EV = {
 'casinos': 'Casino showrooms',
 'festivals': 'Festival stages',
 'venues': 'Clubs & theaters',
 'hotel': 'Hotel bars & lounges',
 'hemp': 'Hemp & cannabis festivals',
 'cultural': 'Cultural events',
 'business': 'Business & private events',
 'after': 'Official after-parties',
}

def yt(id, title, note=''):
    return {'id': id, 'title': title, 'note': note}

ACTS = [
 {
  'slug': 'afroman', 'name': 'Afroman', 'show': 'Because I Got High Tour',
  'since': '1997',
  'photo': 'afroman', 'pos': '50% 30%',
  'region': 'Born in Los Angeles; came up in Palmdale, CA and Hattiesburg, MS',
  'genre': 'Hip-hop, comedy rap',
  'bio': [
   'Afroman turned a homemade song into a worldwide sing-along: "Because I Got High" spread from his own independent releases to a 2002 Grammy nomination for Best Rap Solo Performance.',
   'He first performed in church playing drums and guitar, and his show still has that loose, musical, crowd-first sense of humor.',
   'He has stayed independent and prolific, and it plays as well on a festival field as it does in a casino showroom.',
  ],
  'songs': ['Because I Got High', 'Crazy Rap'],
  'video': yt('WeYsTmIzjkw', 'Afroman - Because I Got High (official, AfromanVEVO)'),
  'socials': [('Website','https://www.ogafroman.com/'),('Instagram','https://www.instagram.com/ogafroman'),('X','https://x.com/ogafroman'),('Facebook','https://www.facebook.com/ogafroman'),('TikTok','https://www.tiktok.com/@ogafroman')],
  'good': ['festivals','hemp','casinos','venues','after'],
  'featured': True,
 },
 {
  'slug': 'rappin-4-tay-x-suga-free', 'name': "Rappin' 4-Tay x Suga Free", 'show': 'The Playaz & Pimps Tour',
  'package': True, 'photo': 'rappin-4-tay', 'pos': '50% 20%',
  'region': 'San Francisco Bay Area + Pomona, CA',
  'genre': 'West Coast hip-hop, G-funk',
  'bio': [
   "A two-headliner bill pairing San Francisco's Rappin' 4-Tay with Pomona's Suga Free: two distinct West Coast voices from the mid-'90s golden era.",
   'Together it gives buyers a full night of radio-era hits and smooth, funk-driven sets that work for a club, a casino or a festival stage.',
  ],
  'members': [
   {
    'slug': 'rappin-4-tay', 'name': "Rappin' 4-Tay", 'photo': 'rappin-4-tay', 'pos': '50% 20%',
    'since': '1988',
    'region': "San Francisco (Fillmore District), CA",
    'genre': 'Bay Area hip-hop',
    'bio': [
     "Rappin' 4-Tay grew up in San Francisco's Fillmore District and got his first break on a Too Short album straight out of high school.",
     'His 1994 album Don\'t Fight the Feelin\' produced "Playaz Club" and "I\'ll Be Around," both Billboard Hot 100 hits, and he later appeared on 2Pac\'s "Only God Can Judge Me."',
     'He has also headlined the main stage at Seattle Hempfest (2013).',
    ],
    'songs': ['Playaz Club', "I'll Be Around", 'Only God Can Judge Me (2Pac feat. Rappin\' 4-Tay)'],
    'video': yt('2daXghqHgjQ', "Rappin' 4-Tay - Playaz Club", 'fan-uploaded video from our one-sheet'),
    'socials': [],
   },
   {
    'slug': 'suga-free', 'name': 'Suga Free', 'photo': 'suga-free', 'pos': '50% 15%',
    'since': '1992',
    'region': 'Pomona, CA',
    'genre': 'West Coast hip-hop, G-funk',
    'bio': [
     'Suga Free came out of Pomona with a rapid, conversational delivery that is instantly recognizable.',
     'His 1997 debut Street Gospel was produced by DJ Quik and introduced "If U Stay Ready," and he has since appeared alongside Snoop Dogg, Xzibit, E-40 and Kokane.',
     'On stage he is equal parts storyteller and showman.',
    ],
    'songs': ['If U Stay Ready', 'On My Way'],
    'video': yt('WLXoSLEm7OQ', 'Suga Free feat. DJ Quik (music video)', 'fan-uploaded video from our one-sheet'),
    'socials': [('Instagram','https://www.instagram.com/officialsugafreethapimp/')],
   },
  ],
  'good': ['venues','casinos','festivals','hemp','after'],
  'featured': True,
 },
 {
  'slug': 'mr-capone-e-x-lil-rob', 'name': 'Mr. Capone-E x Lil Rob', 'show': 'The Puro Loco Tour',
  'package': True, 'photo': 'mr-capone-e', 'pos': '50% 40%',
  'region': 'Southern California (West Covina + San Diego)',
  'genre': 'Chicano rap, West Coast hip-hop, oldies-soul',
  'bio': [
   "Two of Southern California's best-known Chicano rap artists on one bill.",
   'Both are known for mixing lowrider-oldies soul with hip-hop, which makes this package a natural fit for car shows, cultural celebrations, casinos and summer festivals.',
  ],
  'members': [
   {
    'slug': 'mr-capone-e', 'name': 'Mr. Capone-E', 'photo': 'mr-capone-e', 'pos': '50% 40%',
    'since': '2000',
    'region': 'West Covina, CA (born in Pakistan)',
    'genre': 'Chicano rap, West Coast hip-hop',
    'bio': [
     'Born in Pakistan and raised in West Covina, Mr. Capone-E built his career independently through his own label, Hi Power Entertainment, which he founded in 2000.',
     'His oldies-driven albums and collaborations with Nate Dogg, Twista and Snoop Dogg made him a fixture of the SoCal scene.',
     'He brings a loyal, multi-generational crowd.',
    ],
    'songs': ['I Did You Wrong', 'I Like It (feat. Nate Dogg)', "Don't Get It Twisted (feat. Twista)"],
    'video': yt('QC0itpRs8N0', 'Mr. Capone-E - I Did You Wrong (official channel)'),
    'socials': [('Instagram','https://www.instagram.com/mrcaponee/'),('YouTube','https://www.youtube.com/@Hipowermusic')],
   },
   {
    'slug': 'lil-rob', 'name': 'Lil Rob', 'photo': 'lil-rob', 'pos': '50% 30%',
    'since': '1992',
    'region': 'San Diego, CA (raised in Solana Beach)',
    'genre': 'Chicano rap',
    'bio': [
     'Lil Rob was born in San Diego and raised in the La Colonia de Eden Gardens neighborhood of Solana Beach.',
     'His 2005 single "Summer Nights" became a Billboard Hot 100 hit and a warm-weather anthem that crowds still sing word for word.',
     'His catalog runs from early-\'90s street records to smooth, oldies-flavored singles.',
    ],
    'songs': ['Summer Nights', 'Bring Out the Freak in You', 'Oh, What a Night'],
    'video': yt('gvK2HGrBc00', 'Lil Rob - Summer Nights (music video)', 'fan-uploaded video from our one-sheet'),
    'socials': [('Website','https://www.lilrob.com/'),('Instagram','https://www.instagram.com/thereallilrob'),('Facebook','https://www.facebook.com/thereallilrob/')],
   },
  ],
  'good': ['cultural','casinos','festivals','venues','after'],
  'featured': True,
 },
 {
  'slug': 'celly-cel', 'name': 'Celly Cel', 'show': '4 The Skrilla Tour',
  'since': '1992',
  'photo': 'celly-cel', 'pos': '50% 25%',
  'region': 'Vallejo, CA (Bay Area)',
  'genre': 'Bay Area hip-hop',
  'bio': [
   'Celly Cel is a Vallejo original who launched his career on his own Realside Records label in 1992.',
   'His 1996 album Killa Kali, released through Sick Wid It / Jive, carried "It\'s Goin\' Down," a Bay Area staple that was certified Gold by the RIAA in 2026.',
   'He is a longtime collaborator of E-40 and B-Legit, and a go-to for authentic Bay Area slap.',
  ],
  'songs': ["It's Goin' Down", '4 tha Scrilla (feat. E-40 & B-Legit)', 'Lifestyle of a Mack'],
  'video': yt('j1viWrz9mzM', "Celly Cel - It's Goin' Down", 'fan-uploaded video from our one-sheet'),
  'socials': [('Website','https://cellycelworld.com/'),('Instagram','https://www.instagram.com/real_cellycel/'),('X','https://x.com/real_cellycel'),('YouTube','https://www.youtube.com/cellyceltv')],
  'good': ['venues','festivals','hemp','after'],
 },
 {
  'slug': 'rbl-posse', 'name': 'RBL Posse', 'show': 'Still Ruthless Tour',
  'since': '1991',
  'photo': 'rbl-posse', 'pos': '50% 25%',
  'region': 'Hunters Point, San Francisco, CA',
  'genre': 'Bay Area gangsta rap',
  'bio': [
   "RBL Posse came out of San Francisco's Hunters Point in the early '90s, and their self-produced debut single \"Don't Give Me No Bammer\" made the Billboard rap singles chart.",
   'Founding member Black C carries the group forward today and keeps releasing new RBL Posse and solo material.',
   'The set is raw, regional and built for fans of classic Bay Area street rap.',
  ],
  'songs': ["Don't Give Me No Bammer"],
  'video': yt('5FaASNsNuPg', "RBL Posse - Don't Give Me No Bammer", 'fan-uploaded video from our one-sheet'),
  'socials': [],
  'good': ['venues','hemp','festivals','after'],
 },
 {
  'slug': 'dru-down', 'name': 'Dru Down', 'show': 'Pimp of the Year Tour',
  'since': '1993',
  'photo': 'dru-down', 'pos': '50% 25%',
  'region': 'East Oakland, CA',
  'genre': 'Bay Area hip-hop',
  'bio': [
   'Dru Down is an East Oakland rapper (and the son of funk legend Bootsy Collins) who broke out of the Bay Area with his 1994 album Explicit Game.',
   'Its single "Pimp of the Year" crossed onto the Billboard Hot 100, and the follow-up album Can You Feel Me reached the Billboard 200.',
   'He is a flamboyant, high-energy performer and part of Yukmouth\'s Regime collective.',
  ],
  'songs': ['Pimp of the Year', 'Can You Feel Me'],
  'video': yt('HzaqvldQO3I', 'Dru Down - Pimp of the Year (official, DruDownVEVO)', 'replaces a dead link from the one-sheet'),
  'socials': [('YouTube','https://www.youtube.com/@DruDownVEVO')],
  'good': ['venues','festivals','after','hemp'],
 },
 {
  'slug': 'yukmouth', 'name': 'Yukmouth', 'show': '',
  'since': '1993',
  'photo': 'yukmouth', 'pos': '50% 25%',
  'region': 'Oakland, CA',
  'genre': 'Bay Area hip-hop',
  'bio': [
   'Yukmouth is one half of Oakland\'s Luniz, the duo behind the 1995 anthem "I Got 5 on It."',
   'As a solo artist on Rap-A-Lot, his debut double album Thugged Out: The Albulation went gold, and he went on to build his own Smoke-A-Lot Records and The Regime collective.',
   'He is a natural pick for hemp events and nostalgia-heavy crowds.',
  ],
  'songs': ['I Got 5 on It (Luniz)', 'Playa Hata (Luniz)'],
  'video': yt('ERtkpnXLrL4', 'Luniz - I Got 5 On It (feat. Michael Marshall)', 'uploaded by a third-party channel, from our one-sheet'),
  'socials': [],
  'good': ['hemp','festivals','venues','after'],
 },
 {
  'slug': 'brockett-parsons', 'name': 'Brockett Parsons', 'show': '',
  'since': 'With Lady Gaga since 2010',
  'photo': 'brockett-parsons', 'pos': '60% 50%',
  'region': 'Summit, NJ native; based in Los Angeles',
  'genre': 'Keys, jazz, R&B, instrumental',
  'tagline': "Lady Gaga's keyboardist",
  'bio': [
   "Brockett Parsons has been Lady Gaga's keyboard player since 2010, across world tours, network TV and the Super Bowl LI halftime show.",
   'A Berklee-trained player rooted in jazz, R&B and hip-hop, he is also a co-inventor of the PianoArc, a circular 360-degree keyboard that turns a solo set into a spectacle.',
   'He is a polished, versatile pick for hotel lounges, corporate events and upscale after-parties.',
  ],
  'songs': [],
  'known': ['Keyboardist for Lady Gaga (since 2010)', 'Co-inventor of the PianoArc', 'Solo album: The Brockettship'],
  'video': yt('d9gdGvnW9DM', 'Brockett Parsons and the PianoArc', 'from Keyboard magazine\'s channel, from our one-sheet'),
  'socials': [('Instagram','https://www.instagram.com/brockettparsons/'),('PianoArc','https://pianoarc.com/')],
  'good': ['hotel','business','after','casinos','festivals'],
 },
 {
  'slug': 'devin-the-dude', 'name': 'Devin the Dude', 'show': 'Seriously Trippin Tour',
  'since': '1992',
  'photo': 'devin-the-dude', 'pos': '50% 50%', 'photo_is_art': True,
  'region': 'Houston, TX',
  'genre': 'Southern hip-hop',
  'bio': [
   'Devin the Dude is Houston\'s laid-back storyteller, a founding member of the Odd Squad (later the Coughee Brothaz) known for easygoing, funny, everyday songs.',
   'Songs like "Doobie Ashtray" made him a favorite of cannabis culture, and in 2025 he co-created the hemp and cannabis-culture brand Coughee by Devin the Dude.',
   'He is an easy fit for hemp fests and relaxed club nights.',
  ],
  'songs': ['Doobie Ashtray', 'What a Job (feat. Snoop Dogg & André 3000)'],
  'video': yt('2T1jdreS6ko', 'Devin the Dude ft. Snoop Dogg & Andre 3000 - What a Job', 'fan-uploaded video from our one-sheet'),
  'socials': [('Instagram','https://www.instagram.com/devindude420/')],
  'good': ['hemp','festivals','venues','after'],
  'featured': True,
 },
 {
  'slug': 'lil-eazy-e', 'name': 'Lil Eazy-E', 'show': 'Straight Outta Compton Tour',
  'since': '2003',
  'photo': 'lil-eazy-e', 'pos': '50% 25%',
  'region': 'Compton, CA',
  'genre': 'West Coast hip-hop',
  'bio': [
   'Lil Eazy-E is the Compton-born son of N.W.A founder Eazy-E, and he carries the family legacy on stage.',
   'He is president of Rich & Ruthless Records and co-founded Rich & Ruthless Cannabis with his brother.',
   'His show leans on the West Coast classics that built Compton\'s name, which makes it a strong draw for throwback nights and hemp events.',
  ],
  'songs': ["This Ain't a Game (feat. Bone Thugs-N-Harmony)", "It Ain't Over"],
  'video': yt('U4cUwlD1CeU', "Lil Eazy-E - I'm From Compton", 'fan-uploaded video from our one-sheet'),
  'socials': [('Website','https://lileazye.com/'),('Instagram','https://www.instagram.com/lileazy_e/'),('YouTube','https://www.youtube.com/@LilEazyE1')],
  'good': ['venues','hemp','festivals','after'],
 },
 {
  'slug': 'baby-bash', 'name': 'Baby Bash', 'show': "Don't Panic It's Organic Tour",
  'since': '1996',
  'photo': 'baby-bash', 'pos': '60% 30%',
  'region': 'Vallejo, CA; also rooted in Houston, TX',
  'genre': 'Latin hip-hop, pop rap',
  'bio': [
   'Baby Bash is a Vallejo-born rapper and singer who came up through Houston\'s Dope House Records before breaking through nationally.',
   '"Suga Suga" with Frankie J reached the Billboard Hot 100 top ten in 2003, followed by hits like "Baby, I\'m Back" with Akon and "Cyclone" with T-Pain.',
   'His radio-friendly catalog is ideal for casinos, hotel pool parties and summer festivals.',
  ],
  'songs': ['Suga Suga (feat. Frankie J)', "Baby, I'm Back (feat. Akon)", 'Cyclone (feat. T-Pain)'],
  'video': yt('6rgStv12dwA', 'Baby Bash - Suga Suga (official, BabyBashVEVO)'),
  'socials': [('YouTube','https://www.youtube.com/@BabyBashVEVO')],
  'good': ['casinos','festivals','hotel','cultural','after'],
  'featured': True,
 },
 {
  'slug': 'bizarre', 'name': 'Bizarre', 'show': 'Built for Destruction Tour',
  'since': '1995',
  'photo': 'bizarre', 'pos': '50% 30%',
  'region': 'Detroit, MI',
  'genre': 'Hip-hop',
  'tagline': 'of D12',
  'bio': [
   "Detroit's Bizarre is best known as a member of D12, the crew whose debut Devil's Night opened at No. 1 on the Billboard 200.",
   'He sharpened his skills at the rap battles in Detroit\'s Saint Andrew\'s Hall, and his solo debut single "Rockstar" featured Eminem.',
   'His over-the-top humor and D12-era hits make for an unpredictable, high-energy set.',
  ],
  'songs': ['Rockstar', 'Purple Pills (D12)', 'My Band (D12)'],
  'video': yt('FI-2NT0cnYY', 'Bizarre - Rockstar (official music video)'),
  'socials': [('Instagram','https://www.instagram.com/bizarresworld/'),('YouTube','https://www.youtube.com/@itsbizarresworld')],
  'good': ['venues','festivals','after'],
 },
 {
  'slug': 'spice-1', 'name': 'Spice 1', 'show': 'American Nightmare Tour',
  'since': '1988',
  'photo': 'spice-1', 'pos': '50% 40%',
  'region': 'Hayward, CA (Bay Area)',
  'genre': 'Bay Area gangsta rap',
  'bio': [
   'Spice 1 is a Hayward native and one of the pioneers of Bay Area hip-hop.',
   'On Jive Records he released three gold albums (Spice 1, 187 He Wrote and AmeriKKKa\'s Nightmare), and he has kept releasing music ever since.',
   'His set brings early-\'90s West Coast intensity for fans who lived it.',
  ],
  'songs': ['187 Proof', 'Welcome to the Ghetto', 'East Bay Gangsta'],
  'video': yt('kRJA2YrA6qI', 'Spice 1 - 187 Proof (official, Spice1VEVO)'),
  'socials': [('Instagram','https://www.instagram.com/therealspiceone/'),('YouTube','https://www.youtube.com/@Spice1VEVO')],
  'good': ['venues','festivals','hemp','after'],
 },
 {
  'slug': 'kurupt', 'name': 'Kurupt', 'show': "Gotti's Gold Tour",
  'since': '1991',
  'photo': 'kurupt', 'pos': '50% 25%',
  'region': 'Born in Philadelphia; raised in Hawthorne, CA',
  'genre': 'West Coast hip-hop, G-funk',
  'tagline': 'of Tha Dogg Pound',
  'bio': [
   'Kurupt co-founded Tha Dogg Pound with Daz Dillinger in the Death Row era and has been a cornerstone of West Coast rap ever since.',
   'His 1998 solo debut Kuruption! reached the Billboard 200 top ten, powered by "We Can Freak It" and the party favorite "C-Walk."',
   'He is a sharp, seasoned lyricist with a deep catalog of G-funk classics.',
  ],
  'songs': ['We Can Freak It', 'C-Walk', 'New York, New York (Tha Dogg Pound)'],
  'video': yt('EW-uwNivPvw', 'Kurupt - C-Walk', 'fan-uploaded video from our one-sheet'),
  'socials': [('Instagram','https://www.instagram.com/official_kurupt/')],
  'good': ['festivals','casinos','venues','hemp','after'],
  'featured': True,
 },
 {
  'slug': '2nd-ii-none', 'name': '2nd II None', 'show': 'More Than a Player Tour',
  'since': '1987',
  'photo': '2nd-ii-none', 'pos': '50% 50%', 'photo_is_art': True,
  'region': 'Compton, CA',
  'genre': 'West Coast hip-hop',
  'bio': [
   'Compton cousins KK and Gangsta D formed 2nd II None alongside their childhood friend DJ Quik, who produced most of their 1991 self-titled debut.',
   '"Be True to Yourself" and "If You Want It" brought them national attention, and "Up \'N Da Club" later turned up on The Sopranos.',
   'It is a smooth, funk-laced set for classic West Coast crowds.',
  ],
  'songs': ['Be True to Yourself', 'If You Want It', "Up 'N Da Club"],
  'video': yt('lBg7jJyNtzM', '2nd II None - If You Want It', 'fan-uploaded video from our one-sheet'),
  'socials': [],
  'good': ['venues','festivals','after'],
 },
 {
  'slug': 'paul-wall', 'name': 'Paul Wall', 'show': 'Slab God Tour',
  'since': '1998',
  'photo': 'paul-wall', 'pos': '55% 40%',
  'region': 'Houston, TX',
  'genre': 'Houston hip-hop',
  'bio': [
   'Paul Wall is a Houston rapper and DJ who came up through Swishahouse before signing with Atlantic.',
   'His 2005 album The Peoples Champ debuted at No. 1 on the Billboard 200, and his feature on Nelly\'s "Grillz" hit No. 1 on the Hot 100 and earned a Grammy nomination.',
   'He is a crowd-friendly headliner for festivals, casinos and car-culture events.',
  ],
  'songs': ["Sittin' Sidewayz (feat. Big Pokey)", "They Don't Know (feat. Bun B)", 'Grillz (Nelly feat. Paul Wall)'],
  'video': yt('YP_6X35h5Qw', "Paul Wall - They Don't Know (feat. Bun B) (official video, Atlantic Records)", 'replaces a dead link from the one-sheet'),
  'socials': [('Instagram','https://www.instagram.com/paulwallbaby/')],
  'good': ['festivals','casinos','venues','hemp','after'],
  'featured': True,
 },
 {
  'slug': 'digital-underground', 'name': 'Digital Underground', 'show': 'Money B & Young Hump',
  'since': '1987 (Money B since 1989)',
  'photo': 'digital-underground', 'pos': '50% 20%',
  'region': 'Oakland, CA',
  'genre': 'Funk-rap, party hip-hop',
  'tagline': 'feat. Money B & Young Hump',
  'bio': [
   'Digital Underground is the Oakland funk-rap crew behind "The Humpty Dance," and the group that helped launch Tupac Shakur.',
   'Today the show is led by original member Money B, one of only two members to appear on every Digital Underground album, alongside Young Hump.',
   'It is a pure party set of D.U. classics, well suited to festivals, casinos, corporate events and after-parties.',
  ],
  'songs': ['The Humpty Dance', 'Doowutchyalike', 'Kiss You Back', 'I Get Around (2Pac feat. Digital Underground)'],
  'video': yt('PBsjggc5jHM', 'Digital Underground - The Humpty Dance (official 4K video, Tommy Boy)'),
  'socials': [],
  'good': ['festivals','casinos','business','after','venues'],
  'featured': True,
 },
]
